spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/bank
    username: bank_user
    password: bank_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  liquibase:
    enabled: false
